set mf6=d:\codes\git\modflow6-parallel-fork-refactor_checkin\modflow6-parallel\bin\mf6.exe
python run_models.py -mf6 %mf6% -mod  1 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  2 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  3 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  4 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  5 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  6 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  7 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  8 -pre -run_ser
python run_models.py -mf6 %mf6% -mod  9 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 10 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 11 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 12 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 13 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 14 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 15 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 16 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 17 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 18 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 19 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 20 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 21 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 22 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 23 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 24 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 25 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 26 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 28 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 29 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 30 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 31 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 32 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 33 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 34 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 35 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 36 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 37 -pre -run_ser
python run_models.py -mf6 %mf6% -mod 38 -pre -run_ser

pause
